version: "3"
services:
  database:
    image: postgres:10.17
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=admin421"
      - "POSTGRES_DB=registred-tasks"
    ports:
      - 5441:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./postgres_custom:/etc/postgresql
volumes:
  pg-data:
